import json
import re
from datetime import datetime
from api.services.llm_service import generate_text


CURRENT_STACK = {
    "video_model": "FFmpeg + static UI overlay",
    "video_cost": "$0 (open-source, CPU-only)",
    "voice_model": "gTTS (Google Text-to-Speech)",
    "voice_cost": "$0 (free API)",
    "strengths": [
        "Zero cost",
        "Deterministic output",
        "Fast batch processing",
        "No GPU required"
    ],
    "weaknesses": [
        "No true lip-sync",
        "Static UI-based video composition",
        "Darija voice quality is limited — sounds like MSA, not natural Darija"
    ]
}

CANDIDATE_MODELS = {
    "video_models": [
        {"name": "Google Veo API", "type": "video", "status": "GA 2025", "cost": "~$0.05/sec of video"},
        {"name": "Kling 3.0", "type": "video", "status": "Released 2025", "cost": "~$0.03/sec of video"},
        {"name": "Luma Dream Machine", "type": "video", "status": "Released 2025", "cost": "~$0.04/sec of video"}
    ],
    "voice_models": [
        {"name": "ElevenLabs Moroccan Darija voice", "type": "voice", "status": "Available", "cost": "~$0.30/1000 chars"}
    ]
}


def _extract_json(text: str) -> dict:
    cleaned = text.strip()
    cleaned = re.sub(r"^```json\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"^```\s*", "", cleaned)
    cleaned = re.sub(r"\s*```$", "", cleaned)

    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        pass

    match = re.search(r"\{.*\}", cleaned, re.DOTALL)
    if match:
        return json.loads(match.group(0))

    return {}


def generate_rd_comparison_report() -> dict:
    prompt = f"""
You are a Weekly R&D Agent for YQN Pay's AI Marketing Factory.

Your job: compare our current video and voice stack against newer AI models,
and recommend whether to switch.

Our current stack:
- Video: {CURRENT_STACK["video_model"]} (cost: {CURRENT_STACK["video_cost"]})
- Voice: {CURRENT_STACK["voice_model"]} (cost: {CURRENT_STACK["voice_cost"]})
- Strengths: {', '.join(CURRENT_STACK["strengths"])}
- Weaknesses: {', '.join(CURRENT_STACK["weaknesses"])}

Candidate video models to evaluate:
{json.dumps(CANDIDATE_MODELS["video_models"], indent=2)}

Candidate voice models to evaluate:
{json.dumps(CANDIDATE_MODELS["voice_models"], indent=2)}

Context: We produce marketing videos for the Moroccan market.
Consumer content must sound like natural Moroccan Darija, not MSA.
We need to scale to 100 videos per day.

Return ONLY valid raw JSON with this exact structure:
{{
  "comparison": {{
    "darija_naturalness": "which stack is better and why",
    "lip_sync_quality": "which stack is better and why",
    "cost_at_100_videos_per_day": "cost comparison",
    "automation_reliability": "which stack is more predictable"
  }},
  "recommendation": {{
    "voice_model": "recommended voice model for 2026",
    "video_model": "recommended video model for 2026",
    "reasoning": "1-2 sentence explanation",
    "upgrade_priority": "which layer to upgrade first and why"
  }},
  "sample_report_text": "A short paragraph comparing Video A (current) vs Video B (new model), written as if presenting to a non-technical stakeholder."
}}

Rules:
- Be specific about cost numbers
- Consider Moroccan Darija quality as the top priority
- Do not wrap the JSON in markdown
- Do not include explanations outside the JSON
"""

    raw = generate_text(prompt)
    llm_analysis = _extract_json(raw)

    return {
        "generated_at": datetime.now().isoformat(),
        "agent_name": "Weekly R&D Agent",
        "agent_type": "LLM-powered (Groq Llama 3.3 70B)",
        "monitoring_scope": {
            "video_models": [m["name"] for m in CANDIDATE_MODELS["video_models"]],
            "voice_models": [m["name"] for m in CANDIDATE_MODELS["voice_models"]]
        },
        "current_stack": CURRENT_STACK,
        "candidate_models": CANDIDATE_MODELS,
        "llm_analysis": llm_analysis,
        "note": (
            "This report is generated by an AI agent that evaluates the current stack "
            "against candidate models. In production, the candidate list would be "
            "updated automatically from API changelogs and model release RSS feeds."
        )
    }
